name: CI/CD for data package

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: Install dependencies
        run: python -m pip install frictionless
      - run: frictionless validate datapackage.json
